---
#
# Ansible managed
#
repository:
  description: Install and configure openssh on your system.
  homepage: https://buluma.github.io/
  topics: openssh, system, security, ansible, molecule, playbook
